# Generated by Django 2.0 on 2018-02-25 11:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='raster10',
            field=django.contrib.gis.db.models.fields.RasterField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='raster50',
            field=django.contrib.gis.db.models.fields.RasterField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_raster',
            field=django.contrib.gis.db.models.fields.RasterField(null=True, srid=4326),
        ),
    ]
