# Generated by Django 2.0 on 2018-02-25 12:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0002_auto_20180225_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
