# Generated by Django 2.0 on 2018-02-25 15:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0004_auto_20180225_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='raster10',
            field=django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='raster50',
            field=django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_raster',
            field=django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='usercriterion',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
    ]
