# Generated by Django 2.0 on 2018-02-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0005_auto_20180225_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultcommune',
            old_name='id_commune',
            new_name='commune',
        ),
        migrations.RenameField(
            model_name='resultcommune',
            old_name='id_result',
            new_name='result',
        ),
        migrations.RenameField(
            model_name='usercriterion',
            old_name='id_criterion',
            new_name='criterion',
        ),
        migrations.RenameField(
            model_name='usercriterion',
            old_name='id_user',
            new_name='user',
        ),
    ]
